# Generated by Django 3.1.4 on 2021-01-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(default=4)),
                ('columns', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plants_in_garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.plant')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.user'),
        ),
    ]
