# Generated by Django 3.1.4 on 2021-01-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20210107_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='region',
        ),
    ]
