# Generated by Django 3.1.4 on 2021-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_remove_plant_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='columns',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='garden',
            name='rows',
            field=models.IntegerField(default=2),
        ),
    ]
